### ISSUE TITLE
OasisException: The path /var/oasis/oasislmf.json (MDK config. JSON file) is indicated as preexisting but does not exist

### ISSUE THREAD

**Issue by fengfengyuyu** [OasisLMF/OasisEvaluation#12]
hi, I pushed button "create analysis" like the following picture, but the log raised error "OasisException: The path /var/oasis/oasislmf.json (MDK config. JSON file) is indicated as preexisting but does not exist".

I checkd the docker container "coreoasis/model_worker:1.3.3" , there is no file "var/oasis/oasislmf.json" indeed.

thanks for your help!

![图片](https://user-images.githubusercontent.com/11608887/68358677-2ce04f80-0154-11ea-9cba-d091ad1619a7.png)

`
Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task R = retval = fun(*args, **kwargs) File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__ return self.run(*args, **kwargs) File "/home/worker/src/model_execution_worker/tasks.py", line 324, in generate_input GenerateOasisFilesCmd(argv=run_args).run() File "/usr/local/lib/python3.6/site-packages/argparsetree/cmd.py", line 153, in run args = args or self.parse_args() File "/usr/local/lib/python3.6/site-packages/oasislmf/cli/base.py", line 47, in parse_args self.args = super(OasisBaseCommand, self).parse_args() File "/usr/local/lib/python3.6/site-packages/argparsetree/cmd.py", line 59, in parse_args return self.arg_parser.parse_args(self.argv) File "/usr/local/lib/python3.6/argparse.py", line 1734, in parse_args args, argv = self.parse_known_args(args, namespace) File "/usr/local/lib/python3.6/argparse.py", line 1766, in parse_known_args namespace, args = self._parse_known_args(args, namespace) File "/usr/local/lib/python3.6/argparse.py", line 1972, in _parse_known_args start_index = consume_optional(start_index) File "/usr/local/lib/python3.6/argparse.py", line 1912, in consume_optional take_action(action, args, option_string) File "/usr/local/lib/python3.6/argparse.py", line 1824, in take_action argument_values = self._get_values(action, argument_strings) File "/usr/local/lib/python3.6/argparse.py", line 2265, in _get_values value = self._get_value(action, arg_string) File "/usr/local/lib/python3.6/argparse.py", line 2294, in _get_value result = type_func(arg_string) File "/usr/local/lib/python3.6/site-packages/oasislmf/utils/path.py", line 82, in __call__ return as_path(path, self.label, preexists=self.preexists) File "/usr/local/lib/python3.6/site-packages/oasislmf/utils/path.py", line 45, in as_path raise OasisException('The path {} ({}) is indicated as preexisting but does not exist'.format(_path, label)) oasislmf.utils.exceptions.OasisException: The path /var/oasis/oasislmf.json (MDK config. JSON file) is indicated as preexisting but does not exist
`

**Comment by fengfengyuyu** [comment]
Sorry, the problem has been solved, by  git clone newest repo.
